name: Auto Tag

on:
  push:
    branches:
      - main

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: Klemensas/action-autotag@stable
          with:
            GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
            tag_prefix: "v"