name: Docker Image Build

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version
        run: echo VERSION=$(cat package.json | grep version | grep -Poh '\d+\.\d+\.\d+') >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ghcr.io/jollyroger-1989/multisolverr:latest,ghcr.io/jollyroger-1989/multisolverr:${{ env.VERSION }}